# Generated by Django 6.0.2 on 2026-02-20 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0002_lawyer_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='license_id',
        ),
        migrations.AddField(
            model_name='lawyercategory',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyers.subcategory'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='lawyers.state'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='lawyers.legalcategory'),
        ),
    ]
