# Generated by Django 6.0.2 on 2026-02-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0003_remove_lawyer_category_remove_lawyer_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
