# Generated by Django 6.0.2 on 2026-02-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0004_lawyer_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='is_free_consultation',
            field=models.BooleanField(default=False),
        ),
    ]
