# Generated by Django 6.0.2 on 2026-02-21 08:07

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0005_lawyer_is_free_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawyers.city'),
        ),
        migrations.AlterField(
            model_name='lawyercategory',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyers.subcategory'),
        ),
    ]
