# Generated by Django 6.0.2 on 2026-02-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0006_alter_lawyer_city_alter_lawyercategory_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='profile_image',
        ),
    ]
